[[CURRENCIES]]
code="xusheng2"
issuer="GC74CKCFCKB3H3LBCCYXGYOP66O3Z65ANSQTBOKPJ7JIRWEFGPQOQMCS"
name="xusheng2 Test Token"
desc="This is a test token created by Wang Xusheng on Pi Testnet. Total supply: 100,000,000."
image="https://wxs1688.github.io/xusheng2.png"
