[[CURRENCIES]]
code="xusheng"
issuer="GDXVEJXFI6AXJPFWJSIVCX67PLYC622YBR4ECH7ROBUCMIHV2FLZADCS"
name="Wang Xusheng"
desc="This is a test token created on Pi Testnet for learning and demonstration."
image="https://wxs1688.github.io/xusheng.png"
